baseURL = "http://jpweber.io/"
languageCode = "en-us"
title = "jpweber blog"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Jim Weber - All rights reserved"
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"


[params]
  logo = "/images/logo.png"
  description ="Figuring it Out"


[params.author]
  name = "Jim Weber"
  thumbnail = "/images/icon-thumb.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/icon-thumb.png"
  title = "Jim Weber"
  subtitle = "Figuring things out and sharing knowledge!"
  mdtext = '''
I do a lot of work with Kubernetes and Cloud native technologies. I hope something you find here helps you. 
### Kubernauts Unite!
'''

[params.social]
  github = "jpweber"
  twitter = "jpw"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
